import datetime
import ipaddress
import uuid
from _pydecimal import Decimal

import asyncpg

postgres_to_python = {
    'anyarray': list,
    'anyenum': str,
    'anyrange': asyncpg.Range,
    'record': asyncpg.Record,  #: tuple,
    'bit': asyncpg.BitString,
    'varbit': asyncpg.BitString,
    'bool': bool,
    'box': asyncpg.Box,
    'bytea': bytes,
    'char': str,
    'name': str,
    'varchar': str,
    'text': str,
    'xml': str,
    'cidr': ipaddress.IPv4Network,
    'inet': ipaddress.IPv4Network,
    'macaddr': str,
    'circle': asyncpg.Circle,
    'date': datetime.date,
    'time': datetime.time,
    'time with timezone': datetime.time,
    'time without timezone': datetime.time,
    'timestamp': datetime.datetime,
    'timestamp with timezone': datetime.datetime,
    'timestamp without timezone': datetime.datetime,
    'interval': datetime.timedelta,
    'float': float,
    'double precision': float,
    'smallint': int,
    'integer': int,
    'bigint': int,
    'numeric': Decimal,
    'json': str,
    'jsonb': str,
    'line': asyncpg.Line,
    'lseg': asyncpg.LineSegment,
    'money': str,
    'path': asyncpg.Path,
    'point': asyncpg.Point,
    'polygon': asyncpg.Polygon,
    'uuid': uuid.UUID,
}
postgres_to_python_text = {
    'anyarray': 'list',
    'anyenum': 'str',
    'anyrange': 'asyncpg.Range',
    'int4range': 'asyncpg.Range',
    'record': 'asyncpg.Record,  #: tuple',
    'bit': 'asyncpg.BitString',
    'varbit': 'asyncpg.BitString',
    'bool': 'bool',
    'boolean': 'bool',
    'box': 'asyncpg.Box',
    'bytea': 'bytes',
    'char': 'str',
    'name': 'str',
    'varchar': 'str',
    'text': 'str',
    'xml': 'str',
    'cidr': 'ipaddress.IPv4Network',
    'inet': 'ipaddress.IPv4Network',
    'macaddr': 'str',
    'circle': 'asyncpg.Circle',
    'date': 'datetime.date',
    'time': 'datetime.time',
    'time with timezone': 'datetime.time',
    'time without time zone': 'datetime.time',
    'timestamp': 'datetime.datetime',
    'timestamp with timezone': 'datetime.datetime',
    'timestamp without time zone': 'datetime.datetime',
    'interval': 'datetime.timedelta',
    'float': 'float',
    'double precision': 'float',
    'smallint': 'int',
    'integer': 'int',
    'bigint': 'int',
    'numeric': 'Decimal',
    'json': 'str',
    'jsonb': 'str',
    'line': 'asyncpg.Line',
    'lseg': 'asyncpg.LineSegment',
    'money': 'str',
    'path': 'asyncpg.Path',
    'point': 'asyncpg.Point',
    'polygon': 'asyncpg.Polygon',
    'uuid': 'uuid.UUID',
}